[build]
  publish = "public"
  command = "echo 'Deploy de produção - BarberShop Elite'"

[build.environment]
  NODE_VERSION = "18"

# Configurações de processamento
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers de segurança
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; font-src 'self' https://cdnjs.cloudflare.com; img-src 'self' data: https:;"

# Cache para arquivos estáticos
[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Redirects para SPA (Single Page Application)
[[redirects]]
  from = "/test-notifications"
  to = "/test-notifications.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/register/*"
  to = "/index.html"
  status = 200

# Fallback para todas as outras rotas (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
